### ISSUE TITLE
timezone not being used?

### ISSUE THREAD

**Issue by worldlyjohn** [peppeocchi/php-cron-scheduler#13]
First, this is very helpful -- thanks for putting it out!

My server is in UTC, so I'm passing custom timezone to Scheduler as "America/New_York" but it's not taking.  Not affected by `every()->hour('00')` calls but `every()->day('9:30')` is.

any ideas?

**Comment by peppeocchi** [comment]
@worldlyjohn that's a documented feature that never got implemented (probably on some local branch in the early stages).

I am currently working on a v2 of this project and I don't think I'll implement the feature to execute jobs based on a custom timezone. I haven't found a clean way of doing that (could be the reason I didn't implemented it)

**The change I already made on v2 is to use the server timezone instead of a default value (current default is `Europe/Dublin`).**

I'll make the same change on the current version, that should fix the issue you're having now (you won't need to specify a timezone, the scheduler will use the server timezone).

Of course if you can find a clean way of implementing that feature, a PR would be much appreciated.

**Comment by peppeocchi** [comment]
@worldlyjohn [v2](https://github.com/peppeocchi/php-cron-scheduler/releases/tag/v2.0) uses the server timezone, if you wish to update to this version make sure to read the changelog and to adjust your scheduler file as needed.

**Comment by worldlyjohn** [comment]
thanks!
