### ISSUE TITLE
Send Email only on Fail?

### ISSUE THREAD

**Issue by green-plastic** [peppeocchi/php-cron-scheduler#50]
I'm using your script inside a loop. So this is just the chunk that runs in the loop. The code uses Guzzle to hit a URL.

Currently, it sends an email every time a job is run. But, I'm trying to figure out how to only send email if Guzzle gives any status code other than 200... or maybe there is a better way?

```
$scheduler->call(function() use ($siteUrl, $file, $k, $v) {
	$client = new \GuzzleHttp\Client();
	$res = $client->head($siteUrl . $v['url'], [ 'http_errors' => false ]);
	
	$data = [
		'status'   => $res->getStatusCode(),
		'datetime' => date('Y-m-d H:i:s'),
	];
	
	echo json_encode($data);
})
->at($v['runtime'])
->output($file)
->configure([
	'email' => [
		'subject' => "Cron: '{$k}' at {$siteName}",
		'from'      => $config['email']['from'],
		'transport' => $transport,
	]
])
->email([ $toEmail ]);
```

Any ideas on how to set `$toEmail` to `false` inside the anonymous function ... or not send the email?

Thanks.

**Comment by green-plastic** [comment]
I just used SwiftMailer inside the anonymous function and checked if the status code from Guzzle was 200. If not 200, then send an email. I then removed the configure() and email() method calls.

**Comment by peppeocchi** [comment]
@green-plastic sorry for the late reply, yes that's exactly how I would use it.

Another option would be to send the email in the `then` (but I guess because you're using an anonymous function there would be no benefit).

It's an interesting feature that could be integrated in the core if you want to submit a PR for that.
My only question would be what can be considered an error? An exception? I think the exception can work for anonymous functions, but not if you're scheduling a script.

**Comment by green-plastic** [comment]
@peppeocchi The way I laid it out works fine. I use Guzzle to hit a URL. I could get fancier, but mostly just checking that hitting the URL works. Most the URLs that are hit do something fairly basic and log themselves.
