### ISSUE TITLE
problem with exec function

### ISSUE THREAD

**Issue by momohammadi** [peppeocchi/php-cron-scheduler#68]
to many shared hosting provider disabled exec and shel_exec function , can i run it without use exec function ?

**Comment by peppeocchi** [comment]
@momohammadi I know what you mean but this library relies on that function to execute background jobs.
One possible workaround is if you schedule Closures instead of script/commands because those jobs don't need the exec or any other function to work (you might have issues writing to files or to send emails if your hosting provider doesn't allow you to run those commands as well)
